### ISSUE TITLE
Cannot link to an image or video that has an \x on title from another file 

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/cirodown#198]
cirodown eb0a2f5924b5e3a80c5250c39ef8aac65f44bc90

tmp.ciro

```
= tmp

\Image[a]{check=0}
{title=\x[tmp-2]}

== tmp 2
```

tmp2.ciro

```
= tmp2

\x[image-tmp-2]
```

Run:

```
cirodown tmp.ciro
cirodown tmp2.ciro
```

error:

```
convert tmp2.ciro
TypeError: Cannot read property 'given' of undefined
    at html_render_func_x (/home/ciro/bak/git/cirodown/index.js:7481:36)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
    at render_arg (/home/ciro/bak/git/cirodown/index.js:2523:28)
    at x_text (/home/ciro/bak/git/cirodown/index.js:5971:12)
    at x_get_href_content (/home/ciro/bak/git/cirodown/index.js:5623:15)
    at html_render_func_x (/home/ciro/bak/git/cirodown/index.js:7479:41)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
    at render_arg (/home/ciro/bak/git/cirodown/index.js:2523:28)
    at html_render_func_P (/home/ciro/bak/git/cirodown/index.js:3256:19)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
```

This problem was introduced when we merged all the SQL queries, and there was no test for it so we didn't notice.

Previously we were just making the queries as they are needed, and it worked.

But we just don't have the title to header dependency information encoded in our database. Another table here we go.

**Comment by cirosantilli** [comment]
The following very weird three step sequence also blows up, gotta ensure it doesn't anymore later on:

```
1.ciro

```
= tmp

== tmp 2
```

2.ciro

```
= tmp

\Image[a]{check=0}
{title=\x[tmp-2]}
```

3.ciro

```
= tmp

\x[image-tmp-2]

\Image[a]{check=0}
{title=\x[tmp-2]}
```

Run:

```
rm -f out/db.sqlite3; cp 1.ciro tmp.ciro; cirodown tmp.ciro && cp 2.ciro tmp.ciro && cirodown tmp.ciro; cp 3.ciro tmp.ciro && cirodown tmp.ciro
```

outcome:

```
TypeError: Cannot read property 'given' of undefined
    at html_render_func_x (/home/ciro/bak/git/cirodown/index.js:7481:36)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
    at render_arg (/home/ciro/bak/git/cirodown/index.js:2523:28)
    at x_text (/home/ciro/bak/git/cirodown/index.js:5971:12)
    at x_get_href_content (/home/ciro/bak/git/cirodown/index.js:5623:15)
    at html_render_func_x (/home/ciro/bak/git/cirodown/index.js:7479:41)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
    at render_arg (/home/ciro/bak/git/cirodown/index.js:2523:28)
    at html_render_func_P (/home/ciro/bak/git/cirodown/index.js:3256:19)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
    at render_arg (/home/ciro/bak/git/cirodown/index.js:2523:28)
    at html_render_func_Toplevel (/home/ciro/bak/git/cirodown/index.js:7225:18)
    at AstNode.render (/home/ciro/bak/git/cirodown/index.js:319:15)
    at Object.convert (/home/ciro/bak/git/cirodown/index.js:2437:18)
    at async convert_input (/home/ciro/bak/git/cirodown/cirodown:234:18)
    at async convert_path (/home/ciro/bak/git/cirodown/cirodown:286:18)
    at async convert_path_to_file (/home/ciro/bak/git/cirodown/cirodown:384:37)
    at async /home/ciro/bak/git/cirodown/cirodown:1037:18
```
