### ISSUE TITLE
ID conflict with header in another file blows up

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/cirodown#201]
God, but I have a test for it at: https://github.com/cirosantilli/cirodown/blob/593ed7a61cc10e2951552d13dd5b02ab24bf00af/test.js#L4137 it only blows up in with the executable. How is that possible?

Cirodown 593ed7a61cc10e2951552d13dd5b02ab24bf00af

tmp.ciro

```
= tmp

== tmp 2
```

tmp2.ciro

```
= tmp2

== tmp 2
```

run:

```
rm -f out/db.sqlite3 && cirodown tmp.ciro; cirodown tmp2.ciro
```

outcome:

```
convert tmp2.ciro
error: tmp2.ciro:3:1: duplicate ID "tmp-2", previous one defined at file "tmp.ciro" line 3 column 1
UniqueConstraintError [SequelizeUniqueConstraintError]: Validation error
    at Query.formatError (/home/ciro/bak/git/cirodown/node_modules/sequelize/lib/dialects/sqlite/query.js:409:16)
    at Query._handleQueryResponse (/home/ciro/bak/git/cirodown/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at Statement.afterExecute (/home/ciro/bak/git/cirodown/node_modules/sequelize/lib/dialects/sqlite/query.js:246:27) {
  errors: [
    ValidationErrorItem {
      message: 'idid must be unique',
      type: 'unique violation',
      path: 'idid',
      value: null,
      origin: 'DB',
      instance: null,
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  fields: [ 'idid' ],
  parent: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: Ids.idid] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `Ids` (`id`,`idid`,`path`,`ast_json`) VALUES (NULL,\'tmp2\',\'tmp2.ciro\',\'{"macro_name":"H","node_type":"MACRO","source_location":{"line":1,"column":1,"path":"tmp2.ciro"},"first_toplevel_child":true,"is_first_header_in_input_file":true,"split_default":false,"word_count":0,"args":{"level":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":1,"column":1,"path":"tmp2.ciro"},"text":"1","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{},"header_tree_node_word_count":0}],"source_location":{"line":1,"column":1,"path":"tmp2.ciro"}},"title":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":1,"column":3,"path":"tmp2.ciro"},"text":"tmp2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":1,"args":{},"header_tree_node_word_count":1}],"source_location":{"line":1,"column":1,"path":"tmp2.ciro"}}},"header_tree_node_word_count":0}\'),(NULL,\'tmp-2\',\'tmp2.ciro\',\'{"macro_name":"H","node_type":"MACRO","source_location":{"line":3,"column":1,"path":"tmp2.ciro"},"first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{"level":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":3,"column":1,"path":"tmp2.ciro"},"text":"2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{},"header_tree_node_word_count":0}],"source_location":{"line":3,"column":1,"path":"tmp2.ciro"}},"title":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":3,"column":4,"path":"tmp2.ciro"},"text":"tmp 2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":2,"args":{},"header_tree_node_word_count":2}],"source_location":{"line":3,"column":1,"path":"tmp2.ciro"}}},"header_tree_node_word_count":0}\');'
  },
  original: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: Ids.idid] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `Ids` (`id`,`idid`,`path`,`ast_json`) VALUES (NULL,\'tmp2\',\'tmp2.ciro\',\'{"macro_name":"H","node_type":"MACRO","source_location":{"line":1,"column":1,"path":"tmp2.ciro"},"first_toplevel_child":true,"is_first_header_in_input_file":true,"split_default":false,"word_count":0,"args":{"level":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":1,"column":1,"path":"tmp2.ciro"},"text":"1","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{},"header_tree_node_word_count":0}],"source_location":{"line":1,"column":1,"path":"tmp2.ciro"}},"title":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":1,"column":3,"path":"tmp2.ciro"},"text":"tmp2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":1,"args":{},"header_tree_node_word_count":1}],"source_location":{"line":1,"column":1,"path":"tmp2.ciro"}}},"header_tree_node_word_count":0}\'),(NULL,\'tmp-2\',\'tmp2.ciro\',\'{"macro_name":"H","node_type":"MACRO","source_location":{"line":3,"column":1,"path":"tmp2.ciro"},"first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{"level":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":3,"column":1,"path":"tmp2.ciro"},"text":"2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{},"header_tree_node_word_count":0}],"source_location":{"line":3,"column":1,"path":"tmp2.ciro"}},"title":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":3,"column":4,"path":"tmp2.ciro"},"text":"tmp 2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":2,"args":{},"header_tree_node_word_count":2}],"source_location":{"line":3,"column":1,"path":"tmp2.ciro"}}},"header_tree_node_word_count":0}\');'
  },
  sql: 'INSERT INTO `Ids` (`id`,`idid`,`path`,`ast_json`) VALUES (NULL,\'tmp2\',\'tmp2.ciro\',\'{"macro_name":"H","node_type":"MACRO","source_location":{"line":1,"column":1,"path":"tmp2.ciro"},"first_toplevel_child":true,"is_first_header_in_input_file":true,"split_default":false,"word_count":0,"args":{"level":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":1,"column":1,"path":"tmp2.ciro"},"text":"1","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{},"header_tree_node_word_count":0}],"source_location":{"line":1,"column":1,"path":"tmp2.ciro"}},"title":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":1,"column":3,"path":"tmp2.ciro"},"text":"tmp2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":1,"args":{},"header_tree_node_word_count":1}],"source_location":{"line":1,"column":1,"path":"tmp2.ciro"}}},"header_tree_node_word_count":0}\'),(NULL,\'tmp-2\',\'tmp2.ciro\',\'{"macro_name":"H","node_type":"MACRO","source_location":{"line":3,"column":1,"path":"tmp2.ciro"},"first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{"level":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":3,"column":1,"path":"tmp2.ciro"},"text":"2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":0,"args":{},"header_tree_node_word_count":0}],"source_location":{"line":3,"column":1,"path":"tmp2.ciro"}},"title":{"asts":[{"macro_name":"plaintext","node_type":"PLAINTEXT","source_location":{"line":3,"column":4,"path":"tmp2.ciro"},"text":"tmp 2","first_toplevel_child":false,"is_first_header_in_input_file":false,"split_default":false,"word_count":2,"args":{},"header_tree_node_word_count":2}],"source_location":{"line":3,"column":1,"path":"tmp2.ciro"}}},"header_tree_node_word_count":0}\');'
}
```

**Comment by cirosantilli** [comment]
OK, the tests missed it because I wasn't running `IdProvider.update` after the main conversion, only after `convert_before`. By doing that always I repro there.
