### ISSUE TITLE
Image without src crashes cirodown

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/cirodown#59]
At Cirodown 3226b6badee43fd2ca234cbf1397b83909ce7f0c:

```
printf '\Image' | ./cirodown
```

crashes with:

```
/home/ciro/bak/git/cirodown/index.js:2789
    if (ast.validation_output.provider.given) {
                                       ^

TypeError: Cannot read property 'given' of undefined
    at macro_image_video_source (/home/ciro/bak/git/cirodown/index.js:2789:40)
    at Object.caption_number_visible (/home/ciro/bak/git/cirodown/index.js:2823:41)
    at parse (/home/ciro/bak/git/cirodown/index.js:2336:41)
    at Object.convert (/home/ciro/bak/git/cirodown/index.js:1277:13)
    at convert_input (/home/ciro/bak/git/cirodown/cirodown:195:25)
    at Object.<anonymous> (/home/ciro/bak/git/cirodown/cirodown:589:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by cirosantilli** [comment]
Fixed as of 257fec0e69368f2a0d0ae30b0fca9dbe1aea3a69 shows:

```
error: 1:1: missing mandatory argument src of Image
```
