### ISSUE TITLE
Crash on unclosed youtube video

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/cirodown#88]
cirodown bff1a7fa9ca1333a934786d28b86561918ac3569

```
= a

\Video[https://www.youtube.com/watch?v=iIWTRwJlrGo

== b
```

error:

```
/home/ciro/bak/git/cirodown/index.js:1719
    .replace(/&/g, '&amp;')
     ^

TypeError: Cannot read property 'replace' of undefined
    at html_escape_content (/home/ciro/bak/git/cirodown/index.js:1719:6)
    at html_escape_attr (/home/ciro/bak/git/cirodown/index.js:1711:10)
    at x_href (/home/ciro/bak/git/cirodown/index.js:3005:46)
    at x_href_attr (/home/ciro/bak/git/cirodown/index.js:3010:28)
    at html_self_link (/home/ciro/bak/git/cirodown/index.js:1782:14)
    at Macro.caption_prefix [as convert] (/home/ciro/bak/git/cirodown/index.js:3517:52)
    at AstNode.convert (/home/ciro/bak/git/cirodown/index.js:142:19)
    at convert_arg (/home/ciro/bak/git/cirodown/index.js:1503:28)
    at convert_arg_noescape (/home/ciro/bak/git/cirodown/index.js:1518:10)
    at macro_image_video_resolve_params (/home/ciro/bak/git/cirodown/index.js:3244:13)
```

**Comment by cirosantilli** [comment]
No repro 802144f2f2d72ce77b7af0fbdb005f5ac1cb106b
